### ISSUE TITLE
DefaultCredentialsError with GKE cluster (intermittently)

### ISSUE THREAD

**Issue by sbstp** [kubernetes-client/python#1001]
**What happened (please include outputs or screenshots)**:
`kubernetes-python` fails to authenticate properly using the kubernetes config. `kubectl` works fine with the same config. The failure appears to be intermittent, sometimes there is no issue authenticating, sometimes there is.
```
btt/kube.py:3: in <module>
    config.load_kube_config()
venv/lib/python3.6/site-packages/kubernetes-11.0.0a1-py3.6.egg/kubernetes/config/kube_config.py:657: in load_kube_config
    loader.load_and_set(config)
venv/lib/python3.6/site-packages/kubernetes-11.0.0a1-py3.6.egg/kubernetes/config/kube_config.py:469: in load_and_set
    self._load_authentication()
venv/lib/python3.6/site-packages/kubernetes-11.0.0a1-py3.6.egg/kubernetes/config/kube_config.py:203: in _load_authentication
    if self._load_auth_provider_token():
venv/lib/python3.6/site-packages/kubernetes-11.0.0a1-py3.6.egg/kubernetes/config/kube_config.py:218: in _load_auth_provider_token
    return self._load_gcp_token(provider)
venv/lib/python3.6/site-packages/kubernetes-11.0.0a1-py3.6.egg/kubernetes/config/kube_config.py:269: in _load_gcp_token
    self._refresh_gcp_token()
venv/lib/python3.6/site-packages/kubernetes-11.0.0a1-py3.6.egg/kubernetes/config/kube_config.py:278: in _refresh_gcp_token
    credentials = self._get_google_credentials()
venv/lib/python3.6/site-packages/kubernetes-11.0.0a1-py3.6.egg/kubernetes/config/kube_config.py:160: in _refresh_credentials
    'https://www.googleapis.com/auth/userinfo.email'
venv/lib/python3.6/site-packages/google_auth-1.6.3-py3.6.egg/google/auth/_default.py:317: in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
E   google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
```

**What you expected to happen**:
It should authenticate properly on its own.

**How to reproduce it (as minimally and precisely as possible)**:
This is my kube config for gke with the sensible information redacted
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: -redacted-
    server: -redacted-
  name: -redacted-
contexts:
- context:
    cluster: -redacted-
    namespace: mongo-operator
    user: -redacted-
  name: mongo-dev-gke
current-context: mongo-dev-gke
kind: Config
preferences: {}
users:
- name: -redacted-
  user:
    auth-provider:
      config:
        access-token: -redacted-
        cmd-args: config config-helper --format=json
        cmd-path: /usr/lib/google-cloud-sdk/bin/gcloud
        expiry: "2019-11-05T22:55:03Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```
And this is the code I'm using
```python
from kubernetes import config, client

config.load_kube_config()

core_api = client.CoreV1Api()
custom_objects_api = client.CustomObjectsApi()
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`):
```Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.9", GitCommit:"6c1e92d07f5717440f751666d4aad6943015d3cb", GitTreeState:"clean", BuildDate:"2019-10-11T23:14:17Z", GoVersion:"go1.11.13b4", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g., MacOS 10.13.6):
```
NAME="Linux Mint"
VERSION="19.1 (Tessa)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19.1"
VERSION_ID="19.1"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.ubuntu.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=tessa
UBUNTU_CODENAME=bionic
```
- Python version (`python --version`) `Python 3.6.8`
- Python client version (`pip list | grep kubernetes`) `kubernetes (11.0.0a1)`
