### ISSUE TITLE
list_event_for_all_namespaces does not return DELETE events

### ISSUE THREAD

**Issue by pzoxiuv** [kubernetes-client/python#1059]
**What happened (please include outputs or screenshots)**:
Watching `list_event_for_all_namespaces` does not return any events when a Pod is deleted.

I have two scripts: one prints all events with `list_event_for_all_namespaces`, and the other creates and then deletes a Pod.  The watcher prints events while the Pod is starting (pulling container, pulled container, starting container, etc.).  But I don't get any event when the pod is deleted.

**What you expected to happen**:

In the apiserver audit log there are events with type='DELETED' - I expect to see those events returned by `list_event_for_all_namespaces`.

**How to reproduce it (as minimally and precisely as possible)**:
test.yaml:
```
import yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-testing
spec:
  restartPolicy: Never
  containers:
  - image: busybox
    name: pod-testing
    command: ["sleep", "10"]
```
watch.py:
```
from kubernetes import client, config, watch

config.load_kube_config()
v1 = client.CoreV1Api()
w = watch.Watch()
for event in w.stream(v1.list_event_for_all_namespaces):
	print(event)
```

Start watching, `python watch.py`.  In a separate terminal, do `kubectl apply -f test.yaml`, then after the Pod is started do `kubectl delete -f test.yaml`.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`): 1.16
- OS (e.g., MacOS 10.13.6): Centos 7.7.1908
- Python version (`python --version`): 3.6.8
- Python client version (`pip list | grep kubernetes`): 10.0.1
