### ISSUE TITLE
how to create custom resource using kubernetes client

### ISSUE THREAD

**Issue by Abn02** [kubernetes-client/python#1116]
I have below resource yaml and i need to do kubectl apply below yaml.
But as i am creating the resource file inside cluster i dont have kubectl inside the pod. So i am using kubernetes client api to create custom resource.

```
apiVersion: details.students.com/v1
kind: StudentdetailsAPI

metadata:
  name: class-2020
spec:
  # Add fields here
  type: studentdetails
  json:
    name: "Anji"
    status: ACTIVE
    batch: "Y"
    branch_id: 641
    changelist_driven: "Y"
    coverage_flag: "N"
```

# python code:

```
dep = yaml.safe_load(f)
resp = k8s_apps_v1.create_namespaced_deployment(
                         body=dep, namespace="autobuilddetails-system")
```

but above logic not working to create new resource.

could you please suggest me with one example
