### ISSUE TITLE
How do I run kubectl apply-f using the API

### ISSUE THREAD

**Issue by moluzhui** [kubernetes-client/python#1168]
I tried using the Kubernetes API python to execute the `kubect apply` command to deploy and update resources

the kubectl command is as follows:
```
kubectl apply -f export
```
`export` is a `folder` containing `multiple yaml files`, which is generated by `kompose convert -o export`

I only found an alternative API for `kubectl create`, but I didn't find `apply`

How do I implement `kubectl apply` to `create` resources and possible subsequent `updates`

If you know, please let me know. thank you in advance!

**Comment by Sunnykaby** [comment]
maybe you can use replace_XXX api

**Comment by MoShitrit** [comment]
You can look at that example as well https://github.com/kubernetes-client/python/blob/master/kubernetes/utils/create_from_yaml.py

**Comment by vishnu667** [comment]
@MoShitrit create_from_yaml works when we have to create a resource.
Let's say I want to update an annotation or the image create_from_yaml fails with [FailToCreateError](https://github.com/kubernetes-client/python/blob/master/kubernetes/utils/create_from_yaml.py#L165)

**Comment by vishnu667** [comment]
Trying to write a utility [replace_from_yaml](https://github.com/vishnu667/python/blob/replace_from_yaml/kubernetes/utils/replace_from_yaml.py)
But am hitting the error.
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "the name of the object (scheduler-deployment) does not match the name on the URL (airflow)",
  "reason": "BadRequest",
  "code": 400
}
```
The same payload works with `kubectl replace -f ` not sure what am missing.

**Comment by MoShitrit** [comment]
> Trying to write a utility [replace_from_yaml](https://github.com/vishnu667/python/blob/replace_from_yaml/kubernetes/utils/replace_from_yaml.py)
> But am hitting the error.
> 
> ```
> {
>   "kind": "Status",
>   "apiVersion": "v1",
>   "metadata": {
>     
>   },
>   "status": "Failure",
>   "message": "the name of the object (scheduler-deployment) does not match the name on the URL (airflow)",
>   "reason": "BadRequest",
>   "code": 400
> }
> ```
> 
> The same payload works with `kubectl replace -f ` not sure what am missing.

What's the value of `kind` from this line, in the error you're getting?
https://github.com/vishnu667/python/blob/replace_from_yaml/kubernetes/utils/replace_from_yaml.py#L156

**Comment by vishnu667** [comment]
This is the payload Am passing
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment_time: '2020-05-22 12:39:38.324272'
  labels:
    app: scheduler
  name: scheduler-deployment
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      annotations:
        deployment_time: '2020-05-22 12:39:38.324286'
      labels:
        app: scheduler
    spec:
      containers:
      - args:
        - scheduler
        env:
        - name: AIRFLOW__KUBERNETES__NAMESPACE
          value: airflow
        image: airflow_base:local
        imagePullPolicy: IfNotPresent
        name: scheduler
      serviceAccountName: airflow-scheduler-serviceaccount
```
If you can point me in the right direction I might be able to write down both these functionalities replace and apply.
