### ISSUE TITLE
how to create a security context?

### ISSUE THREAD

**Issue by buxizhizhoum** [kubernetes-client/python#1181]
how to create a security context? I have tried 
```
security_context = {
            "privileged": True,  #  "privileged": "true" is also tried, 
            "capabilities": {
                "add": ["SYS_ADMIN"]
            }
        }
```
the corresponding yaml config is:
```
securityContext:
      privileged: true
      capabilities:
        add:
          - SYS_ADMIN
```

however it is not working, I just wonder what else could I do? or is there an example?
