### ISSUE TITLE
to_dict() of `model` should respect attribute_map

### ISSUE THREAD

**Issue by bukowa** [kubernetes-client/python#1228]
While running [to_dict](https://github.com/kubernetes-client/python/blob/master/kubernetes/client/models/admissionregistration_v1beta1_webhook_client_config.py#L135) method on the model attribute_map is not respected.
````python
    attribute_map = {
        'service_name': 'serviceName',
        'service_port': 'servicePort'
    }
````
This results in bad yaml
````yaml
  - host: example.com
    http:
      paths:
      - backend:
          service_name: example-service
          service_port: 8080
        path: /
````
related:
- https://github.com/kubernetes-client/python/issues/1117
- https://github.com/OpenAPITools/openapi-generator/issues/4586 (looks like a fix included)
- https://github.com/OpenAPITools/openapi-generator/issues/4586
