### ISSUE TITLE
read_namespaced_pod_log with follow=True hangs when there is a long gap between logs from pod

### ISSUE THREAD

**Issue by 0xdholleran** [kubernetes-client/python#1234]
**What happened (please include outputs or screenshots)**:
If I try to read the logs of a pod with the following:
```
from kubernetes import config, client
config.load_incluster_config()
k8s = client.CoreV1Api()
namespace = "default"
pod_name="watch-this"
logs = k8s.read_namespaced_pod_log(
    name=pod_name,
    namespace=namespace,
    follow=True,
    _preload_content=False,
)
for line in logs:
  print(line)
```

 and there is a gap (say 5 minutes)  between line1 and line2 of the log being written, then the function hangs after the first line

**What you expected to happen**:

the function should read all the logs as they are written from the watched pod and then exit once finished

**How to reproduce it (as minimally and precisely as possible)**:

Create the following pod to watch:
```
apiVersion: v1
kind: Pod
metadata:
  name: watch-this
  namespace: default
spec:
  containers:
  - command:
    - python3
    - -u
    - -c
    - |
      from time import sleep
      for i in range(3):
        print(i)
        if i != 2:
          sleep(300)
    image: python:3.7.4-slim-stretch
    imagePullPolicy: IfNotPresent
    name: python
    resources: {}
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
```

then watch the pod with the following:
```
kubectl -n default run -i -t test-python-kube-client --image=python:3.7.4-slim-stretch --restart=Never --command -- /bin/sh

pip install kubernetes==11.0.0
python
from kubernetes import config, client
config.load_incluster_config()
k8s = client.CoreV1Api()
namespace = "default"
pod_name="watch-this"
logs = k8s.read_namespaced_pod_log(
    name=pod_name,
    namespace=namespace,
    follow=True,
    _preload_content=False,
)
for line in logs:
  print(line)
```

the output should get stuck like this:
`b'0\n'`

however if I run the equivalent request using kubectl proxy and the kubernetes API, it works as expected:
```
kubectl proxy --port=8080 &
curl http://localhost:8080/api/v1/namespaces/default/pods/watch-this/log?follow=true
0
1
2
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.13", GitCommit:"1da71a35d52fa82847fd61c3db20c4f95d283977", GitTreeState:"clean", BuildDate:"2020-07-15T21:59:26Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`):
- OS ( MacOS 10.14.6):
- Python version (`3.7.4`)
- Python client version (`kubernetes==11.0.0`)
