### ISSUE TITLE
How to get the current pod's namespace

### ISSUE THREAD

**Issue by love-miao** [kubernetes-client/python#1288]
**Link to the issue (please include a link to the specific documentation or example)**:

**Description of the issue (please include outputs or screenshots if possible)**:

I run it in a pod.
I want to get the current pod's namespace。
Is there such a method？

**Comment by MoShitrit** [comment]
@love-miao if I understand your need correctly- you are trying to figure out which namespace does a currently active pod runs in? If that's the case, I wouldn't use the Python client for that, there's a much easier way that doesn't require any coding.
Take a look at the [Downward API](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/). For example, to expose a pod's namespace, simply add this to your pod spec:
```yaml
      env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
```
