### ISSUE TITLE
I need a list of dicts or something for data

### ISSUE THREAD

**Issue by rlewkowicz** [kubernetes-client/python#1318]
I need a config map that looks something like:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::[redact]:role/workers
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::[redact]:role/AWS-SSO-Admin
      username: admin:{{SessionName}}
      groups:
        - system:masters
```

Maybe this is a documentation issue, but I've tried dicts, lists of dicts, tuples. I can't even start to build this object. I was hoping to avoid walls of text or template files as I wanted to build these objects dynamically. I'm sure I could still use python strings creatively, but being able to build it with native python data types would be cool.
```
configmap = client.V1ConfigMap(
        api_version="v1",
        kind="ConfigMap",
        data={"mapRoles":[{"foo":"bar"},{"foo":"baz"}]}, << what goes here?
        metadata=metadata
    )
```
