### ISSUE TITLE
Submitting strings as a block scalar 

### ISSUE THREAD

**Issue by rlewkowicz** [kubernetes-client/python#1328]
You can build a config map, but for various things, they are just strings. The aws auth config map for example:
ku --namespace kube-system get cm aws-auth -o yaml
```
data:
  mapRoles: |
    - rolearn: arn:aws:iam::[REDACT]:role/[REDACT]-us-east-2-workernode
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
```
If I submitted a similar entry via this library, it's suddenly very ugly:
```
  mapRoles: "- rolearn: arn:aws:iam::[REDACT]:role/[REDACT]-workers\n  username: system:node:{{EC2PrivateDNSName}}\n
    \ groups:\n    - system:bootstrappers\n    - system:nodes
```
I think the underlying rest client converts this all into json so thats why this happens.

Is there a way to define your submission as a block scalar?
