### ISSUE TITLE
ConfigMapVolume miss field: ConfigMap

### ISSUE THREAD

**Issue by findsomeoneyys** [kubernetes-client/python#1338]
**What happened (please include outputs or screenshots)**:
for example, if i had created a config map like
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-conf
data:
  my.conf: |

    [options]
    db_name = xxx
```
then when creating `Deployment Volume` use `V1ConfigMapVolumeSource` object, it will spec as
```
volumes:
  - name: my-conf
        
```

**What you expected to happen**:
what i expected is like this:
```
volumes:
 - name: my-conf
   configMap:
     name: my-conf
```
but `V1ConfigMapVolumeSource` object hasn't `configMap` fields
