### ISSUE TITLE
How do we do rolling restart?

### ISSUE THREAD

**Issue by nsubrahm-aws** [kubernetes-client/python#1378]
How do we do `kubectl rollout restart deployment your_deployment_name` ? I couldn't locate appropriate documentation for this.

**Comment by MoShitrit** [comment]
@nsubrahm-awsI believe the best way would be to use the [`patch deployment`](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/AppsV1Api.md#patch_namespaced_deployment) function and add a dummy annotation to the `spec.template.metadata.annotations` block. This should trigger the creation of a new replicaset and automatically handle the restart based on the `strategy` specified in the deployment spec.
That is also what `kubectl rollout restart deployment` does behind the scenes. 
When you run `kubectl rollout restart deployment`, it adds a `kubectl.kubernetes.io/restartedAt` annotation which contains a timestamp, like this one:
```yaml
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2021-02-15T11:12:54-05:00"
```
