### ISSUE TITLE
Need a function to get cluster info from kubeconfig

### ISSUE THREAD

**Issue by artiship** [kubernetes-client/python#1391]
**What is the feature and why do you need it**:

I need to submit jobs to multiple clusters to rebalance the computing workload. Once a cluster context gets chosen the better is that I can also get the corresponding API server URL.

**Describe the solution you'd like to see**:

A standard cluster config in kubeconfig is like this:

```
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ2ekNDQXRPZ0F3SUJBZ0lERTJyL01BMEdDU3FHU0liM0RRRUJDd1VBTUdveEtqQW9CZ05WQkFvVElXTXcKWldaalptWmpaR0V4TWpFMFl6Q.....
    server: https://kube-apiserverxxxxx.cn:6443
  name: cluster-1
```

Maybe there should be a function like this to get the cluster info

```
config.getClusterInfo()
config.getClusterInfoByContext()

or 

contexts, active_context = config.list_kube_config_contexts()
clusterInfos = [context.getClusterInfo for context in contexts]
```
