### ISSUE TITLE
Update the CRD yaml manifest mentioned in custom_object example

### ISSUE THREAD

**Issue by Priyankasaggu11929** [kubernetes-client/python#1432]
**Link to the issue (please include a link to the specific documentation or example)**:

https://github.com/kubernetes-client/python/blob/master/examples/custom_object.py#L22-L38

**Description of the issue (please include outputs or screenshots if possible)**:

The [custom_object.py](https://github.com/kubernetes-client/python/blob/master/examples/custom_object.py) uses a Custom Resource Definition (CRD) to create a custom object. And so, it mentions to apply the[ following yaml manifest](https://github.com/kubernetes-client/python/blob/master/examples/custom_object.py#L22-L38) first (before executing the example script):

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct
``` 
But on applying the above yaml manifest, it throws the following error:

```
The CustomResourceDefinition "crontabs.stable.example.com" is invalid: spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required
```
