### ISSUE TITLE
Container with configMap not working. 

### ISSUE THREAD

**Issue by m1nish1208** [kubernetes-client/python#1635]
**What happened (please include outputs or screenshots)**:
I'm trying to add configMaps to a pod while creating a POD using create_namespaced_pod method.
 
**What you expected to happen**:
Expecting POD to be created using configMap defined in the spec. 

**How to reproduce it (as minimally and precisely as possible)**:
Attaching code snippet for reference.
https://gist.github.com/m1nish1208/fa84aa7538f8265a0b7a4962790700c1 

**Environment**:
- Kubernetes version: microk8s v1.22.4
- OS: Ubuntu LTS 20.04 
- Python version: 3.6.9
- Python client version: kubernetes (19.15.0)

**Comment by schneesu** [comment]
@m1nish1208 your code logic is messy
1. func `create_configmap` just generate configmap manifest but not create a configmap in cluster
2. pod_manifest.spec.containers.envFrom + configMapRef require an existed configmap, what's more, just need configmap's name, like this:
```
apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - configMapRef:
          name: special-config   <<< cm'name only
  restartPolicy: Never
```

Ref: [Configure all key-value pairs in a ConfigMap as container environment variables](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#configure-all-key-value-pairs-in-a-configmap-as-container-environment-variables)
