### ISSUE TITLE
create_namespaced_custom_object returns 404

### ISSUE THREAD

**Issue by cham-d** [kubernetes-client/python#1684]
**What happened (please include outputs or screenshots)**:
I tried to use create_namespaced_custom_object but i'm getting HTTP response body: 404 page not found
![image](https://user-images.githubusercontent.com/55649286/150978344-612ca11c-f4bb-4973-bf56-43d9d286a5ad.png)
I use k3d locally.

**How to reproduce it (as minimally and precisely as possible)**:
```
def applyyamlfile(yamlfile,namespace):    
    config.load_kube_config()
    k8s_api = client.CustomObjectsApi()
    group = 'split.smi-spec.io' 
    version = 'v1alpha1' 
    namespace = namespace 
    plural = 'TrafficSplit' 
    body=yaml.safe_load(yamlfile) 
    api_response = k8s_api.create_namespaced_custom_object(group, version, namespace, plural, body)
```

```
yamlfile = "apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: traffic-split-v3
  namespace: default
spec:
  service: productcatalogservice
  backends:
  - service: productcatalogservice-first
    weight: 900m
  - service: productcatalogservice
    weight: 100m"
```

`namespace = 'default'`

**Environment**:
- Kubernetes version (`kubectl version`): _v1.22.4_
- OS (e.g., MacOS 10.13.6): _Ubuntu 20.04_
- Python version (`python --version`) _3.8.10 (i also tried 3.6.15)_
- Python client version (`pip list | grep kubernetes`) _21.0.0-snapshot_
