### ISSUE TITLE
The problem with creating multiple resource objects using YAML

### ISSUE THREAD

**Issue by dbdocker** [kubernetes-client/python#1757]
Error:
![image](https://user-images.githubusercontent.com/66933220/159112864-e4945923-6e6a-47d9-8ed7-f301fa3dfeb5.png)

Source code:
![image](https://user-images.githubusercontent.com/66933220/159112923-7c754bb4-5224-4135-8260-b4172c0d84e2.png)

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
#  namespace: public-open-test
  name: mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongo
#  namespace: liandaojqxxh
  labels:
    app: mongo
    version: v1
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo
      containers:
        - name: mongo-server
          image: 'mongo:4'
          ports:
            - name: tcp-27017
              containerPort: 27017
              protocol: TCP
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: VpOXN7vbhcgq2IJL
          resources:
            limits:
              cpu: '1'
              memory: 1500Mi
            requests:
              cpu: 500m
              memory: 500Mi
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
            - name: mongo-data
              mountPath: /data/db
          imagePullPolicy: IfNotPresent
      restartPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: mongo
#  namespace: jgj-sheyangats
  labels:
    app: mongo
spec:
  ports:
    - name: tcp-27017
      protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: mongo
  type: ClusterIP
```

Only one Deployment object can be created. No other objects can be created.
