### ISSUE TITLE
utils.create_from_dict fails for custom objects

### ISSUE THREAD

**Issue by NaxAlpha** [kubernetes-client/python#1792]
**What happened (please include outputs or screenshots)**:

I want to do something like `kubectl apply -f <yaml-file>` but with python kubernetes api client that is dynamically generated for different clusters. I have a Knative distribution running on a cluster but when I run `utils.create_from_dict` on a loaded knative yaml object, it fails and gives the following error:

```
Traceback (most recent call last):
  File "/Users/🙈/Documents/redox-backend/base/kluster.py", line 64, in <module>
    utils.create_from_dict(kube, obj, True)
  File "/opt/homebrew/anaconda3/envs/main/lib/python3.9/site-packages/kubernetes/utils/create_from_yaml.py", line 216, in create_from_dict
    created = create_from_yaml_single_item(
  File "/opt/homebrew/anaconda3/envs/main/lib/python3.9/site-packages/kubernetes/utils/create_from_yaml.py", line 242, in create_from_yaml_single_item
    k8s_api = getattr(client, fcn_to_call)(k8s_client)
AttributeError: module 'kubernetes.client' has no attribute 'ServingKnativeDevV1Api'
```

From the basic inspection of the error stack it seems a lot of work to implement `ServingKnativeDevV1Api`. I want to ask if there is a quick workaround as I don't need all the functionality of `ServingKnativeDevV1Api` object but need to just apply updates to YAML object.

**What you expected to happen**:

No error, successfully configure the patched yaml like kubectl does.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a new cluster
2. Install [Knative](https://knative.dev/docs/install/).
3. Use the following yaml file:
```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "5"
    spec:
      containerConcurrency: 50
      containers:
      - image: <sample-image>
        ports:
        - containerPort: 8000
```
4. Load yaml file as dict object in python
5. Run `utils.create_from_dict` for that object.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6-gke.300", GitCommit:"df413ee6225aa3fc539e18ca3464a48d723bd3ea", GitTreeState:"clean", BuildDate:"2022-01-24T09:29:08Z", GoVersion:"go1.16.12b7", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g., MacOS 10.13.6): MacOS 12.3.1
- Python version (`python --version`): 3.9.9
- Python client version (`pip list | grep kubernetes`): 23.3.0
