### ISSUE TITLE
Can't use client in combination with oracle cloud oci -> Unauthorized

### ISSUE THREAD

**Issue by max-os-lg** [kubernetes-client/python#1807]
**What happened (please include outputs or screenshots)**:
I am trying to use the client in combination with a oracle cloud kubernetes configuration file.  
The K8 config file is set via environment file and in python I call `config.load_kube_config(context=context)`  

The user part of my ocl k8 config file looks like this:  

```yaml
user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: oci
      args:
      - ce
      - cluster
      - generate-token
      - --cluster-id
      - ocid1.cluster.oc1.blabla
      - --region
      - eu-frankfurt-1
      env: []
```
My other configurations for different cloud providers are working but they also don't have this `command` executed for retrieving a token. They have the token already inside the config written.  

So my guess is, that the python client has a problem with this config file.

**What you expected to happen**:
That valid kube configs are working with the python client also.  

**How to reproduce it (as minimally and precisely as possible)**:
Try using the `oci` command inside the kube config file.  

**Environment**:
- Kubernetes version (`kubectl version`): client (1.24) and server (1.22)
- OS (e.g., MacOS 10.13.6): Ubuntu 20.04
- Python version (`python --version`): 3.8.13
- Python client version (`pip list | grep kubernetes`): 23.6.0
