### ISSUE TITLE
create_from_yaml not raising an exception on failure

### ISSUE THREAD

**Issue by ghost** [kubernetes-client/python#1864]
**What happened (please include outputs or screenshots)**:
[create_from_yaml ](https://github.com/kubernetes-client/python/blob/master/kubernetes/utils/create_from_yaml.py) is not raising a "FailToCreateError" exception when the contents of the yaml fail to apply.

The result from create_from_yaml clearly shows a failure, for the right reasons (my example is attempting to create a job in a non-existent namespace. But the failure is not caught by the "FailToCreateError" exception as suggested by the documentation.

![image](https://user-images.githubusercontent.com/71513313/180476591-8e8b3d4f-9751-482a-8970-b2fdedfc473f.png)

**What you expected to happen**:
I expect a "FailToCreateError" exception to be raised to allow handling of errors applying the contents yaml files.

**How to reproduce it (as minimally and precisely as possible)**:
Using local Kind cluster the following script and yaml file will report "Test job created" when in fact the job is never created.

```
from loguru import logger
from kubernetes import client, config
from kubernetes.utils import create_from_yaml, FailToCreateError

def run_job(k8s_client, job_definition_file):
    try:
        status = create_from_yaml(k8s_client, job_definition_file, verbose=False, async_req=True)
    except FailToCreateError:
        logger.error(f"This should fail but never does")
        return False
    except ValueError as e:
        logger.error(str(e))
        return False
    except FileNotFoundError as e:
        logger.error(str(e))
        return False
    else:
        logger.info(f"Test job created")
        return status

config.load_kube_config()
k8s_client = client.ApiClient()

job_file = "path/to/job.yaml"
run_job(k8s_client, job_file)
```
Example job yaml file contents:

```
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: non-existant-namespace
  name: test-job
spec:
  template:
    metadata:
      labels:
        app: test-job
    spec:
      containers:
        - name: test-job
          image: some-image:latest
          imagePullPolicy: IfNotPresent
```

**Anything else we need to know?**:
Believe it to be caused by [create_from_yaml_single_item](https://github.com/kubernetes-client/python/blob/0553bba32dd5f2029a086131c893f0b295ac4297/kubernetes/utils/create_from_yaml.py#L229) not raising an exception up to the higher functions.

**Environment**:
- Kubernetes version: 1.24.2
- OS: Fedora 36
- Python version: 3.10
- Python client version: 24.2.0

Edit: missing words.
