### ISSUE TITLE
Cannot completely ignore SSL verification with OIDC authenticated Kubernetes - doing load_kube_config

### ISSUE THREAD

**Issue by chanjaljayaram** [kubernetes-client/python#1900]
Trying to completely ignore the SSL verification by removing the idp-certificate-authority-data field from the kubeconfig. Sample kubeconfig
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: XXXXXXXXX
    server: https://X.X.X.X:443
  name: cluster-1
contexts:
- context:
    cluster: cluster-1
    user: user-1
  name: context-1
current-context: context-1
kind: Config
preferences: {}
users:
- name: user-1
  user:
    auth-provider:
      config:
        client-id: my_client_id
        client-secret: ''
        id-token: XXXXXXXXXXXXXX
        idp-issuer-url: https://myidp:443/oauth/token
        #idp-certificate-authority-data: XXXXXXXXX
        refresh-token: XXXXXXXXXXX
      name: oidc
```
I got it working after making the below code change in kube_config.py (Function _refresh_oidc). The line "verify=config.ssl_ca_cert if config.verify_ssl else **None**" was changed to "verify=config.ssl_ca_cert if config.verify_ssl else **False**"
```
        try:
            refresh = request.refresh_token(
                token_url=response['token_endpoint'],
                refresh_token=provider['config']['refresh-token'],
                auth=(provider['config']['client-id'],
                      provider['config']['client-secret']),
                verify=config.ssl_ca_cert if config.verify_ssl else False
            )
        except oauthlib.oauth2.rfc6749.errors.InvalidClientIdError:
            return
```
