### ISSUE TITLE
Couldn't replicate the way kubectl applies to patch an update to a job object via patch_namespaced_job

### ISSUE THREAD

**Issue by ozlerhakan** [kubernetes-client/python#1999]
**What happened (please include outputs or screenshots)**:

I would like to produce the same approach where I update the job object as follows:
```
$ kubectl patch job my-job -p '{"metadata": {"finalizers": []}}' --type merge
```

**What you expected to happen**:

I expect that the following code performs the same behaviour as kubectl but no luck:

```
body = {"metadata": {"finalizers": []}}
batch.patch_namespaced_job(
        "my-job", namespace="my-namespace", body=body,
        field_manager='MergePatch', field_validation='Strict'
)
```
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

I set debug to True and could't find any errors.
 
**Environment**:
- Kubernetes version (`kubectl version`):

```
clientVersion:
  buildDate: "2022-09-21T14:33:49Z"
  compiler: gc
  gitCommit: 5835544ca568b757a8ecae5c153f317e5736700e
  gitTreeState: clean
  gitVersion: v1.25.2
  goVersion: go1.19.1
  major: "1"
  minor: "25"
  platform: darwin/arm64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2022-12-08T19:51:45Z"
  compiler: gc
  gitCommit: b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d
  gitTreeState: clean
  gitVersion: v1.26.0
  goVersion: go1.19.4
  major: "1"
  minor: "26"
  platform: linux/arm64
```
- OS (e.g., MacOS 10.13.6):
- Python version (`python --version`)
```
python --version                                                                                                                          
Python 3.11.1
```
- Python client version (`pip list | grep kubernetes`)
```
kubernetes          25.3.0
```
