### ISSUE TITLE
Is there any method to create service and deployment at the same time?

### ISSUE THREAD

**Issue by hjxgitcode** [kubernetes-client/python#2208]
I wrote a nginx. yaml that contains deployment and service, but only one resource can be created. How can we create it like
`kubectl apply -f nginx.yaml`
```
with open('nginx.yaml') as f:
    file = yaml.safe_load(f)
    nginxCreate = v1.create_namespaced_service(namespace='default', body=file)
    print(nginxCreate)
``` 
nginx.yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testnginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testnginx
  template:
    metadata:
      labels:
        app: testnginx
    spec:
      containers:
      - name: nginx
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: testnginx
spec:
  type: NodePort 
  ports:
  - protocol: TCP
    port: 8081 
    targetPort: 80 
    name: test
  selector:
    app: testnginx
``` 
error:
``` 
yaml.composer.ComposerError: expected a single document in the stream
  in "nginx.yaml", line 1, column 1
but found another document
  in "nginx.yaml", line 19, column 1
```
