### ISSUE TITLE
What is the method to create a new resource type？

### ISSUE THREAD

**Issue by hjxgitcode** [kubernetes-client/python#2211]
My cluster extends kubevirt, which can **kubectl apply - f testvm.yaml**，But an error occurs when I try to create resources with client.
client code:
```
from kubernetes import client, config, utils

config.load_kube_config('config')

v1 = client.CoreV1Api()
v2 = client.AppsV1Api()
k8s_client = client.ApiClient()

file = 'yamlfile\\testvm.yaml'
utils.create_from_yaml(k8s_client, file, verbose=True)
```

error:
`
AttributeError: module 'kubernetes.client' has no attribute 'KubevirtIoV1Api'
`

testvm.yaml:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=
---
apiVersion: v1
kind: Service
metadata:
  name: vm-ssh
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 24
    targetPort: 22
    name: test
  selector:
    kubevirt.io/domain: testvm
    kubevirt.io/size: small
```
