### ISSUE TITLE
Mounting a Persistent Volume Claim as Volume within a Pod's Container spec doesn't seem to work.

### ISSUE THREAD

**Issue by dtm2451** [kubernetes-client/python#2217]
**What happened (please include outputs or screenshots)**:
A pod is created from the manifest below, but the `volume` meant to target a persistent_volume_claim is instead created as EmptyDir, and container volume_mounts meant to target this volume are skipped entirely.

Specifically, when I run `kubectl describe pod/test-pod`, its container has no mount associated with the target name, and I see the below for the volume that should be a PersistentVolumeClaim:
```
Volumes:
  vulcan-cache:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
```

**What you expected to happen**:
I expect the pod to be created with
```
Volumes:
  vulcan-cache:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  vulcan-cache-claim
    ReadOnly:   false
```
and its container to have
```
   Mounts:
      /running from vulcan-cache (rw)
```

*I was able to successfully produce this by spinning up the pod up from an equivalent yml file and using kubectl directly.*

**How to reproduce it (as minimally and precisely as possible)**:

1. Set up a persistent volume and persistent volume claim.  Create yml files containing the below...

Persistent volume config: (Adjust 'path' as needed to something that exists on your k8s node) 
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vulcan-cache
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: "/home"
    type: Directory
```

Persistent Volume Claim config:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vulcan-cache-claim
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: vulcan-cache
```

Then run `kubectl create -f path/to/each/config.yml` for both files.

2. Use kubernetes client to try to spin up a pod from this manifest.  (assuming you don't need or want description of how to establish `kub_cli` here)

```
pod_manifest = {
    'apiVersion': 'v1',
    'kind': 'Pod',
    'metadata': {
        'name': "test-pod",
        'namespace': 'default',
    },
    'spec': {
        "volumes": [{
            "name": "vulcan-cache",
            "persistent_volume_claim": {"claim_name": "vulcan-cache-claim"},
            }],
        'containers': [{
            'name': 'test-container',
            'image': 'nginx',
            'image_pull_policy': 'IfNotPresent',
            "args": 
                ["ls", "/running"],
            "volume_mounts":  [{
                "name": "vulcan-cache",
                "mount_path": "/running",
                }]
        }],
    }
}
kub_cli.create_namespaced_pod(body=pod_manifest, namespace='default')
```

**Anything else we need to know?**:

I am newer to working with kubernetes, but I believe this methodology is the intended way to mount persistent storage to pod containers, https://kubernetes.io/docs/concepts/storage/persistent-volumes/#claims-as-volumes

**Environment**:
- Kubernetes version (`kubectl version`):
```
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3
```
- OS (e.g., MacOS 10.13.6): Linux, Pop!_OS 22.04
- Python version (`python --version`): 3.10.12 and 3.8.17. (MRE tested directly only with 3.10.12)
- Python client version (`pip list | grep kubernetes`): 29.0.0
