### ISSUE TITLE
Unclear Usage of V1ConfigMap

### ISSUE THREAD

**Issue by Annieharamad** [kubernetes-client/python#2263]
[**Link to the issue (please include a link to the specific documentation or example)**:](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1ConfigMap.md)

![image](https://github.com/user-attachments/assets/79b93548-eefe-46e3-bbf1-fffcf976a385)

I'm looking for a way to practically "convert" into kubernetes-client code a ConfigMap yaml file and provide it to a V1PodSpec which feeds into V1Pod; However, I've haven't found a clear cut way to execute that, for the reason of unclear documentation and many objects of V1ConfigMapsEtc that are provided in the picture.

If someone can shed some light about how I can perform the following, or point me to some existing example.

An example config map yaml here

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"

  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true    
```
