### ISSUE TITLE
CRD status is not deployed

### ISSUE THREAD

**Issue by leonp-c** [kubernetes-client/python#2268]
**What happened:
Registering a CRD with:
```
subresources:
      scale:
        labelSelectorPath: .status.selector
        specReplicasPath: .spec.replicas
        statusReplicasPath: .status.replicas
      status: {}
```
is not registered in k8s. after testing from command line using `kubectl get crd some.custom.crd.ai -o yaml`
the result yaml is:
```
    subresources:
      scale:
        labelSelectorPath: .status.selector
        specReplicasPath: .spec.replicas
        statusReplicasPath: .status.replicas
```
status is missing

**What you expected to happen**:
status should exist so that using kubernetes command (kubernnetes package):
`custom_objects_api.get_namespaced_custom_object(group=self.group, version=self.version, namespace=self.namespace, plural=self.plural, name=self.name)`
would work

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a `CustomResourceDefinition` resource that has `spec.versions.subresources.status` as {} (dict)
check the deployed CRD resource yaml
`get crd some.resource.name.ai -o yaml`

**Anything else we need to know?**:
Tried to downgrade to kubernetes 28.1.0, same result to comply to hikaru version (1.3.0)

**Environment**:
- Kubernetes version (`kubectl version`):
  - Client Version: v1.27.2
  - Kustomize Version: v5.0.1
  - Server Version: v1.27.14
  - OS (e.g., MacOS 10.13.6):
- Python version (`python --version`): 3.10.12
- Python client version (`pip list | grep kubernetes`): 30.1.0
- hikaru version: 1.3.0
