### ISSUE TITLE
Empty auth-provider/config key raises ConfigException

### ISSUE THREAD

**Issue by pbrumblay** [kubernetes-client/python#328]
I'm trying to write a dockerized application to crawl k8s clusters and extract configuration information. I don't wish to install gcloud/kubectl in the application container so I'm following this suggestion on constructing a kube config file: https://github.com/kubernetes/kubernetes/issues/30617#issuecomment-290785866

With this config file:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <REDACTED>
    server: https://<REDACTED>
  name: foo-cluster
contexts:
- context:
    cluster: foo-cluster
    user: foo-cluster
  name: foo-cluster
current-context: foo-cluster
kind: Config
preferences: {}
users:
- name: foo-cluster
  user:
    auth-provider:
      config: null
      name: gcp
```

And this code:
```
from kubernetes import config, client

config.load_kube_config('myconfig')
```

I get this error:
```
<SNIP!>
  File "/Users/peter/python3/py3/lib/python3.6/site-packages/kubernetes/config/kube_config.py", line 196, in _load_gcp_token
    self._refresh_gcp_token()
  File "/Users/peter/python3/py3/lib/python3.6/site-packages/kubernetes/config/kube_config.py", line 204, in _refresh_gcp_token
    provider = self._user['auth-provider']['config']
  File "/Users/peter/python3/py3/lib/python3.6/site-packages/kubernetes/config/kube_config.py", line 290, in __getitem__
    % (key, self.name))
kubernetes.config.config_exception.ConfigException: Invalid kube-config file. Expected key config in kube-config/users[name=foo-cluster]/user/auth-provider
```

The key is present - what the heck? This threw me for a while until I cracked open the code. 

I believe this is because line 203 of https://github.com/kubernetes-client/python-base/blob/ab3fc5446714ac19100c0f97072c53cbd81c3b87/config/kube_config.py sets the value to the empty dict {} and line 287 in `__getitem__` only tests for boolean true (and empty dicts are False in python).

My workaround is to add a bogus attribute under config to my yaml file to make the dict non-empty. It appears that the *intent* is to allow people to have missing/empty/invalid/expired auth-provider/config entries and to then generate the config entry when such a case is detected. I'm new to python but I suppose this is a common problem because of the way that python evaluates empty dicts to False.

I'm not sure what the right fix would be, whether to have `__getitem__` allow empty structures or to simply add a bogus value to make the dict non-empty in line 203. Or maybe I should have just known this and tried adding a bogus attribute to config right off the bat...
