### ISSUE TITLE
Dictionary representations of k8s resource model objects are not valid k8s resource manifest representations

### ISSUE THREAD

**Issue by RochesterinNYC** [kubernetes-client/python#390]
My use case is that I'd like to build up a representation of various Kubernetes resources via the classes in `kubernetes.client.models` and then generate the manifest yaml files for these resources via printing to YAML files the `to_dict`representations of these resource objects. However, because all the attributes are snake cased, the end YAML also has snake cased keys (which are not valid k8s manifest keys and fail validation). 

Example:

```
with open('deployment.yaml, 'w') as outfile:
    yaml.dump(deploymemnt_resource.to_dict(), outfile, default_flow_style=False)
```

Resulting `deployment.yaml` file:

```
api_version: extensions/v1beta1
kind: Deployment
metadata:
  name: testing
spec:
  progress_deadline_seconds: 300
  replicas: 1
  template:
    metadata:
      labels:
        app: testing
    spec:
      containers:
      - name: testing
        readiness_probe:
          http_get:
            path: /_meta/0/info
            port: http
```
The `progress_deadline_seconds`, `readiness_probe`, and `http_get` keys are all invalid.
