### ISSUE TITLE
Namespaced PersistentVolumes not handled

### ISSUE THREAD

**Issue by msnelling** [kubernetes-client/python#498]
I'm using your library through the Ansible k8s_raw module and I'm getting the error `method read_namespaced_persistent_volume not found for model persistent_volume` when trying to create the following object
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test
  namespace: test
spec:
  capacity:
    storage: 3Ti
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 1.2.3.4
    path: /Share
```
The module works correctly when the namespace item is omitted.
