### ISSUE TITLE
Invalid kube-config file. Expected key user in kube-config/users[name=xxx]

### ISSUE THREAD

**Issue by xychu** [kubernetes-client/python#518]
Got `Invalid kube-config file. Expected key user in kube-config/users[name=admin]` when use
kube-config file like:
```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: http://192.168.56.102:8080
  name: vm
contexts:
- context:
    cluster: vm
    user: admin
  name: vm
current-context: vm
kind: Config
preferences: {}
users:
- name: admin
  user: {}
```
or
```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: http://192.168.56.102:8080
  name: vm
contexts:
- context:
    cluster: vm
    user: admin
  name: vm
current-context: vm
kind: Config
preferences: {}
users:
- name: admin

```

but `kubectl ` works well with both content.
