### ISSUE TITLE
Deployment with initializers creation succeeds, but reports with exception

### ISSUE THREAD

**Issue by mrow4a** [kubernetes-client/python#544]
### Environment
- Kubernetes cluster v1.10
- Initializers enabled
- python-kubernetes v6.0.0

### Description

I have the following deployment

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sparkoperator
  namespace: sparkoperator
  labels:
    app.kubernetes.io/name: sparkoperator
    app.kubernetes.io/version: v2.3.0-v1alpha1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sparkoperator
      app.kubernetes.io/version: v2.3.0-v1alpha1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sparkoperator
        app.kubernetes.io/version: v2.3.0-v1alpha1
      initializers:
        pending: []  
    spec:
      serviceAccountName: sparkoperator
      volumes:
      - name: spark-default-config
        configMap:
          name: spark-default-config
      containers:
      - name: sparkoperator
        image: gitlab-registry.cern.ch/db/spark-service/docker-registry/spark-on-k8s-operator:v1alpha1
        imagePullPolicy: Always
        command: ["/usr/bin/spark-operator"]
        env:
          - name: SPARK_CONF_DIR
            value: /opt/spark/conf
        volumeMounts:
          - name: spark-default-config
            mountPath: /opt/spark/conf
        args:
        - -logtostderr
        - -enable-initializer=true
```

However when I create the deployment with below I can see deployment is being successfully created, but there is an exception raised
```
api_instance = client.AppsV1beta1Api(self.k8s_client)
api_instance.create_namespaced_deployment(namespace=namespace, body=object_loaded)
```

I get 
```
   return self.__deserialize_model(data, klass)
  File "/Library/Python/2.7/site-packages/kubernetes/client/api_client.py", line 622, in __deserialize_model
    instance = klass(**kwargs)
  File "/Library/Python/2.7/site-packages/kubernetes/client/models/v1_initializers.py", line 52, in __init__
    self.pending = pending
  File "/Library/Python/2.7/site-packages/kubernetes/client/models/v1_initializers.py", line 77, in pending
    raise ValueError("Invalid value for `pending`, must not be `None`")
ValueError: Invalid value for `pending`, must not be `None`
```

Is it me using below wrongly, or python package did not expect such case? Not sure if I should approach with fix as I could be doing it wrong
```
      initializers:
        pending: []  
```

Note: I don't have this issue with `kubectl`
