### ISSUE TITLE
Create Persistence Volume Claim fails to auto-create related PV

### ISSUE THREAD

**Issue by nagapavan** [kubernetes-client/python#564]
Creating a PVC fails to automatically create related PV.

Template Used
```yaml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs
  namespace: ${TENANT_ID}
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
```

`API Call:`
```python
api_instance.create_namespaced_persistent_volume_claim(namespace=namespace_name,
                                                                                     body=_efs_pvc_template_yaml)
```

OS : Linux (CentOS 7.x)
Python Version: 2.7.13
Python Client version: 6.0.0
