### ISSUE TITLE
Creating a Persistence Volume (PV) is not automatically creating related `nfs` path directory

### ISSUE THREAD

**Issue by nagapavan** [kubernetes-client/python#565]
Since #564 is not working, tried creating a PV through API.

Template used:
```yaml
{
  "apiVersion": "v1",
  "kind": "PersistentVolume",
  "metadata": {
    "name": "pv-efs-{{{NameSpace}}}",
    "namespace": "{{{NameSpace}}}",
    "labels": {
      "volume-type": "efs",
      "aws-availability-zone": "{{{AWS_REGION}}}",
      "namespace": "{{{NameSpace}}}"
    }
  },
  "spec": {
    "capacity": {
      "storage": "1Gi"
    },
    "accessModes": [
      "ReadWriteMany"
    ],
    "persistentVolumeReclaimPolicy": "Delete",
    "storageClassName": "efs",
    "nfs": {
      "path": "/efs-pvc-{{{RandomId}}}",
      "server": "{{{FileSystemId}}}.efs.{{{AWS_REGION}}}.amazonaws.com"
    }
  }
}
```

PV creation works, but it doesn't take care of auto creating specified `path`. The same template invoked through `kubectl` does auto-creation of `path` on NFS `server`
