### ISSUE TITLE
read_namespaced_ingress returns underscore named attribute (instead) of camelCase

### ISSUE THREAD

**Issue by huahyong** [kubernetes-client/python#574]
Hello, 
when I create with kubectl a simple Ingress  such as:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: www.foo.com
    http:
      paths:
      - path: /
        backend:
          serviceName: egg
          servicePort: 8080
      - path: /bar
        backend:
          serviceName: spam
          servicePort: 8090
```
I can read it with `kubectl get ingress myingress -o json >test-ingress.json`  and obviously get:
````
{ "apiVersion": "extensions/v1beta1",
    "kind": "Ingress",
    "metadata": {
        "annotations": {
   ...... 
        },
        .......
    },
    "spec": {
        "rules": [{
                "host": "www.foo.com",
                "http": {
                    "paths": [{
                            "backend": {
                                "serviceName": "egg",
                                "servicePort": 8080
                            },
                            "path": "/"
                        },
                        {
                            "backend": {
                                "serviceName": "spam",
                                "servicePort": 8090
                            },
                            "path": "/bar"
                        }
                    ]
......
}
````
When I try to get the same result with: `ingress = extv1.read_namespaced_ingress('myingress', 'default')` I get:
```
{'api_version': 'extensions/v1beta1',
 'kind': 'Ingress',
 'metadata': {'annotations': {
........
},
.......
'spec': {'backend': None,
          'rules': [{'host': 'www.foo.com',
                     'http': {'paths': [{'backend': {'service_name': 'egg',
                                                     'service_port': 8080},
                                         'path': '/'},
                                        {'backend': {'service_name': 'spam',
                                                     'service_port': 8090},
                                         'path': '/bar'}]}}],
...
```
the problem is that the attributes `serviceName and servicePort` are replaced by `service_name and service_port`. If I try to manipulate this object eg. adding a path, the methods `patch_namespaced_ingress` and `replace_namespaced_ingress` complain that serviceName is none
I can replace back them easily, but I this the right way? 
Thank you for your time.
