### ISSUE TITLE
Load config fails with `env: null` in users/user/exec section

### ISSUE THREAD

**Issue by Lawouach** [kubernetes-client/python#637]
Hey there,

Client: 8.0.0a1
Server: Kubernetes 1.10.3
Provider: EKS

I created a cluster using [eksctl](https://eksctl.io/) and the generated kubeconf has the entry `env: null` under `users/user/exec` to which the client responds with:

```
ERROR:root:Invalid kube-config file. Expected key env in kube-config/users[name=iam-some-account@my-cluster.us-west-2.eksctl.io]/user/exec
```

When I remove the key entirely, it works nicely. When I fill the key with dictionary entries, it works too. I can only assume either `env: null` is invalid (then I will open a ticket on eksctl) or the client should support it.

Thanks,

**Comment by errordeveloper** [comment]
hey @Lawouach, thanks for finding and reporting this! Is this coming from Python client or some other one? Arguably, all client should tolerate this (`null` vs `{}` or `[]`), as `kubectl` and `k8s.io/client-go` do. The reason this is causing an issue, as it's to do with exec authentication plugin, which is still an alpha API (`client.authentication.k8s.io/v1alpha1`).

```
- name: ilya@unique-hideout-1536840907.us-west-2.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - unique-hideout-1536840907
      command: heptio-authenticator-aws
      env: null
```

So to me this looks like two bugs actual bugs, what do you think?
