### ISSUE TITLE
Create applications  kubernetes.client.rest.ApiException: (403)

### ISSUE THREAD

**Issue by 1032231418** [kubernetes-client/python#644]
It is not possible to create pod, but it is okay to create namespace.

```
#coding=utf8
from kubernetes import client, config
from os import path
import  yaml
data ={"apitoken": "xxxxxxx","apihost": "xxxxx"}
ApiToken = data['apitoken']
configuration = client.Configuration()
setattr(configuration, 'verify_ssl', False)
configuration.host =  data['apihost']
configuration.verify_ssl = False
configuration.debug = True
configuration.api_key = {"authorization": "Bearer " +  data['apitoken']}
client.Configuration.set_default(configuration)


with open(path.join(path.dirname(__file__), "nginx-deployment.yaml")) as f:
    dep = yaml.load(f)
    print (dep)
    k8s_beta = client.AppsV1beta2Api(client.ApiClient(configuration))
    resp = k8s_beta.create_namespaced_deployment(
            body=dep, namespace="default")
    print("Deployment created. status='%s'" % str(resp.status))
```

```
# cat rbac.yaml 
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]


---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: pods-list
  apiGroup: rbac.authorization.k8s.io
```

![1](https://user-images.githubusercontent.com/5716348/46843787-0e037280-ce07-11e8-802b-acb6598d0386.png)
