### ISSUE TITLE
while deleting a Job, error "no kind Job is registered for version batch/v1".

### ISSUE THREAD

**Issue by neeraj9194** [kubernetes-client/python#664]
while deleting a job with `batch_v1.delete_namespaced_job(name=name, body=body, namespace=namespace)`
I am getting "no kind Job is registered for version batch/v1" error but the delete works fine with kubectl. The `create_namespaced_job` works fine. It only delete which gives this error.
I also tried with this  simple example, still same error.
```
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
```
```
ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Audit-Id': '572a0bc3-7164-413a-a4c8-c2a77d351f87', 'Content-Type': 'application/json', 'Date': 'Fri, 26 Oct 2018 21:52:48 GMT', 'Content-Length': '147'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"no kind \"Job\" is registered for version \"batch/v1\"","code":500}
```
