### ISSUE TITLE
CoreV1Api APIs work but ApiClient.call_api() does not

### ISSUE THREAD

**Issue by jbell-shibumi** [kubernetes-client/python#720]
I'm having an issue, it seems that the built in, pythonized API calls (such as CoreV1Api, where the responses are wrapped in python objects) work, but calling `client.ApiClient().call_api()` results in a 401 unauthorized response...

I'm using a token based authentication, which is stored in the config file itself. See below

Code:
```
from kubernetes import client, config

config.load_kube_config()

coreV1_client = client.CoreV1Api()
api_client = client.ApiClient()

# This works (apparently this is authorized?) ...
pods = coreV1_client.list_pod_for_all_namespaces()

# This does not work (401 unauthorized)
metrics = api_client.call_api('/apis/metrics.k8s.io/v1beta1/pods', 'GET')
```

Config
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED
    server: REDACTED
  name: MyCluster
contexts:
- context:
    cluster: MyCluster
    namespace: MyCluster
    user: MyCluster
  name: MyCluster
current-context: MyCluster
kind: Config
preferences: {}
users:
- name: MyCluster
  user:
    token: REDACTED
```
