### ISSUE TITLE
CoreV1Api patch_namespaced_service couldn't update the port number with the same port name

### ISSUE THREAD

**Issue by adoo123** [kubernetes-client/python#800]
According to the example for CoreV1Api create_namespaced_service,I create a service with my nginx pod,yaml looks like this:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: test-nginx
  namespace: default
  labels:
    app: test-nginx
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: test-nginx
  sessionAffinity: None
  type: ClusterIP
```
It was created successfully.But when i use CoreV1Api patch_namespaced_service with newly yaml like this:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: test-nginx
  namespace: default
  labels:
    app: test-nginx
spec:
  ports:
  - name: http
    port: 81
    protocol: TCP
    targetPort: 81
  selector:
    app: test-nginx
  sessionAffinity: None
  type: ClusterIP
```
It failed to update with:
```
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Service \"test-nginx\" is invalid: spec.ports[1].name: Duplicate value: \"http\"","reason":"Invalid","details":{"name":"test-nginx","kind":"Service","causes":[{"reason":"FieldValueDuplicate","message":"Duplicate value: \"http\"","field":"spec.ports[1].name"}]},"code":422}
```
It looks like to create a new port with this service, not update the port, and the port's name is the same, when i use "kubectl apply" to update this yaml(use corev1api to create and use kubectl apply to update) ,it's already response this failed.When I use "kubectl apply" create and update this yaml ,it's succeed!
So what's the different with "kubectl apply" and "patch_namespaced_service",and could you please help me to fix it?
