### ISSUE TITLE
V1HorizontalPodAutoscalerSpec seems to be outdated

### ISSUE THREAD

**Issue by EmanekaT** [kubernetes-client/python#914]
Hello, I noticed that V1HorizontalPodAutoscalerSpec only supports target_cpu_utilization_percentage. It seems I can't add multiple metrics or custom resouces/metrics like 

```yaml
apiVersion: autoscaling/v2beta1 
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: AverageUtilization
        averageUtilization: 50
  - type: Pods
    pods:
      metric:
        name: packets-per-second
      targetAverageValue: 1k
  - type: Object
    object:
      metric:
        name: requests-per-second
      describedObject:
        apiVersion: networking.k8s.io/v1beta1
        kind: Ingress
        name: main-route
      target:
        kind: Value
        value: 10k
```
